version: '3.3'
services:
  minecraft:
    build: .
    restart: unless-stopped
    ports:
      - '25565:25565'
    volumes:
      - './minecraft:/minecraft'
    read_only: true
    tty: true
    stdin_open: true
