name: Publish Images

on: [push]

jobs:
  github_registry:
    name: Publish to GitHub Cointainer Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Docker QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ GITHUB.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64,linux/386
          push: true
          tags: |
            ${{ GITHUB_REPOSITORY }}:latest
            ghcr.io/${{ GITHUB_REPOSITORY }}:latest
